name: Lint 
on:
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        go-version:
          - 1.17.x
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code
        uses: actions/checkout@v1
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest 
      - name: Test
        run: go test -v ./...