name: Release build 
on:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        go-version:
          - 1.17.x
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code
        uses: actions/checkout@v1
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest 
      - name: Test
        run: go test -v ./...
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=version::$(git describe --tags --abbrev=0 | sed 's/^.//')"
      - name: Build docker image
        run: VERSION=${{ steps.vars.outputs.version }} make docker-build
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push docker image to DockerHub
        run: |
          docker push neohsudroid/project-ci:${{ steps.vars.outputs.version }} 